apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  database: mysql
  database_uri: mysql://localhost:3306
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-env
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
    - configMapRef:
        name: my-cm
    command:
    - "bin/sh"
    - "-c"
    - "echo My Database = $database - $database_uri"
  restartPolicy: Never

