apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
  namespace: default
data:
# Database connection
  database: mysql
  database_uri: mysql://localhost:3306

#User interface
  font.title: Arial Bold
  background-color: red
  theme.1: clean
  theme: dark
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-env
  labels:
    name: pod-cm-env
spec:
  containers:
  - name: my-env-container
    image: nginx
    envFrom:
      - configMapRef:
          name: my-config-map
