apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deply
spec:
  selector:
    matchLabels:
      app: frontend-deply
  template:
    metadata:
      labels:
        app: frontend-deply
    spec:
      containers:
      - name: frontend-deply
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  replicas: 4
