apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
  labels:
    name: resource-pod
spec:
  containers:
  - name: resource-pod
    image: httpd
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        cpu: "1000m"
        memory: "256Mi"
