apiVersion: v1
kind: Pod
metadata:
  name: my-container
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - secretRef:
        name: my-secret
        optional: true
    volumeMounts:
      - name: my-vol
        mountPath: "/etc/my-vol"
        readOnly: true
  volumes:
  - name: my-vol
    secret:
      secretName: my-secret
      optional: true 