apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
spec:
  containers:
  - name: redis-pod
    image: redis
    volumeMounts:
    - name: "cache-storage"
      mountPath: "my-volume"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: cache-storage
    emptyDir: {}
